#!/bin/bash

xrdb /home/thinker/.Xdefaults
/home/thinker/scripts/wal.sh&
setxkbmap -layout us,ru -variant -option grp:caps_toggle,terminate:ctrl_alt_bksp &
kbdd &
pamusb-agent &
(mocp -S)&
(sleep 1 && trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand false --height 14 --transparent true --alpha 0 --tint 0x221818 --margin 20 --width 8 --distancefrom center --distance 400)&
(sleep 2 && wicd-client -t -a)&
(sleep 2 && blueman-applet)&
xscreensaver -no-splash &
(sleep 3 && thunar --daemon)&
(sleep 3 && xfsettingsd)&
exec xmonad
