#!/bin/bash
wicd-client -t -a&
/home/thinker/scripts/wal.sh&
xscreensaver -no-splash&
xrdb /home/thinker/.Xdefaults&
xfsettingsd&
pamusb-agent&
setxkbmap -layout us,ru -variant -option grp:caps_toggle,terminate:ctrl_alt_bksp &
kbdd &
trayer --edge top --align center --SetDockType true --SetPartialStrut true --expand true --height 14 --transparent true --alpha 0 --tint 0x221818 --margin 20 --width 6 --distancefrom center --distance -300&
dropbox start&
blueman-applet&
exec xmonad
